// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow for the AI Chatbot to provide anxiety management techniques and guidance.
 *
 * - aiChatbotAnxietyManagement - A function that handles the anxiety management process.
 * - AIChatbotAnxietyManagementInput - The input type for the aiChatbotAnxietyManagement function.
 * - AIChatbotAnxietyManagementOutput - The return type for the aiChatbotAnxietyManagement function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AIChatbotAnxietyManagementInputSchema = z.object({
  userInput: z.string().describe('The user input text.'),
  moodScore: z.number().describe('The mood score of the user, ranging from 1 to 10.'),
});
export type AIChatbotAnxietyManagementInput = z.infer<typeof AIChatbotAnxietyManagementInputSchema>;

const AIChatbotAnxietyManagementOutputSchema = z.object({
  response: z.string().describe('The response from the AI chatbot providing anxiety management techniques and guidance.'),
});
export type AIChatbotAnxietyManagementOutput = z.infer<typeof AIChatbotAnxietyManagementOutputSchema>;

export async function aiChatbotAnxietyManagement(input: AIChatbotAnxietyManagementInput): Promise<AIChatbotAnxietyManagementOutput> {
  return aiChatbotAnxietyManagementFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiChatbotAnxietyManagementPrompt',
  input: {schema: AIChatbotAnxietyManagementInputSchema},
  output: {schema: AIChatbotAnxietyManagementOutputSchema},
  prompt: `You are a mental health chatbot designed to provide anxiety management techniques and guidance to students.

  A student has come to you seeking help, they provided the following information:
  User Input: {{{userInput}}}
  Mood Score (1-10): {{{moodScore}}}

  Based on the user's input and mood score, suggest specific anxiety management techniques. Consider the following techniques:

  *   Deep Breathing Exercises: Guide the user through a deep breathing exercise.
  *   Mindfulness Meditation: Suggest a short mindfulness meditation exercise.
  *   Progressive Muscle Relaxation: Explain how to perform progressive muscle relaxation.
  *   Cognitive Restructuring: Help the user identify and challenge negative thought patterns.
  *   Grounding Techniques: Recommend grounding techniques to help the user feel more present.

  Provide a supportive and encouraging response, tailored to the user's situation. Offer practical steps and resources that the user can utilize to manage their anxiety.
  Response:`, 
});

const aiChatbotAnxietyManagementFlow = ai.defineFlow(
  {
    name: 'aiChatbotAnxietyManagementFlow',
    inputSchema: AIChatbotAnxietyManagementInputSchema,
    outputSchema: AIChatbotAnxietyManagementOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
